version: "3"

services:
  devproj:
    image: devproj:latest

    build:
      context: .

    ports:
      - 8080:8080

    depends_on:
      - postgres

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/devproj
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  

  postgres:
    image: postgres

    expose:
      - 5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devproj